### ISSUE TITLE
Icon fonts 404

### ISSUE THREAD

**Issue by MaxGabriel** [ltext/ltext.github.io#1]
I'm getting 404s for the icon fonts:

![image](https://cloud.githubusercontent.com/assets/1274145/7904205/8cdef68a-07a7-11e5-891f-2f3c9bd68aca.png)

![image](https://cloud.githubusercontent.com/assets/1274145/7904208/abc4c688-07a7-11e5-8932-6f8ec6688c36.png)

Browser: 43.0.2357.81
OS: OS X 10.10.3

**Comment by athanclark** [comment]
Well that's a great start :P. I've changed back to local deployments, it should work now. Can you test it again? Sorry about this.

**Comment by athanclark** [comment]
Actually, because of the traffic, I think github will wait before "switching over" to the version I just deployed. It might take a while :\
